'use client';
import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { useDoctorAuthStore } from '@/store/doctorAuthStore';
import { prescriptionService, patientService } from '@/services/doctorApi.service';
import { Prescription, PrescriptionMedication, PatientProfile } from '@/types';
import toast from 'react-hot-toast';
import {
  Loader2, Plus, Search, Printer, X, FileText, Pill,
  Clock, CheckCircle, AlertCircle, Ban,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const STATUS_CONFIG: Record<string, { label: string; color: string; icon: React.FC<{ className?: string }> }> = {
  draft:     { label: 'Draft', color: 'bg-gray-500/10 text-gray-600', icon: Clock },
  active:    { label: 'Active', color: 'bg-green-500/10 text-green-600', icon: CheckCircle },
  completed: { label: 'Completed', color: 'bg-blue-500/10 text-blue-600', icon: CheckCircle },
  cancelled: { label: 'Cancelled', color: 'bg-red-500/10 text-red-600', icon: Ban },
};

const DURATION_UNITS = ['days', 'weeks', 'months'] as const;

function emptyMedication(): PrescriptionMedication {
  return {
    name: '', dosage: '', morning: false, afternoon: false,
    evening: false, night: false, duration: '', durationUnit: 'days', instructions: '',
  };
}

export default function PrescriptionsPage() {
  const router = useRouter();
  const { isAuthenticated, _hydrated } = useDoctorAuthStore();
  const [prescriptions, setPrescriptions] = useState<Prescription[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [showBuilder, setShowBuilder] = useState(false);

  useEffect(() => {
    if (_hydrated && !isAuthenticated) router.replace('/doctor/login');
  }, [_hydrated, isAuthenticated, router]);

  const fetchPrescriptions = useCallback(async () => {
    if (!isAuthenticated) return;
    try {
      const res = await prescriptionService.getAll();
      setPrescriptions(res.data.data || []);
    } catch { /* ignore */ }
    setLoading(false);
  }, [isAuthenticated]);

  useEffect(() => { fetchPrescriptions(); }, [fetchPrescriptions]);

  if (!_hydrated || !isAuthenticated) return null;

  const filtered = searchQuery
    ? prescriptions.filter(p =>
        p.patient?.name?.toLowerCase().includes(searchQuery.toLowerCase())
      )
    : prescriptions;

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this prescription?')) return;
    try {
      await prescriptionService.delete(id);
      setPrescriptions(prev => prev.filter(p => p._id !== id));
      toast.success('Prescription deleted');
    } catch { toast.error('Failed to delete'); }
  };

  const handlePrint = (p: Prescription) => {
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`
      <html><head><title>Prescription</title>
      <style>body{font-family:Arial,sans-serif;padding:40px}
      h1{font-size:20px;margin-bottom:4px}p{margin:2px 0;color:#555}
      table{width:100%;border-collapse:collapse;margin-top:16px}
      th,td{text-align:left;padding:8px;border-bottom:1px solid #ddd}
      th{background:#f5f5f5}.footer{margin-top:24px;font-size:12px;color:#999}
      </style></head><body>
      <h1>Prescription</h1>
      <p><strong>Patient:</strong> ${p.patient?.name || 'N/A'}</p>
      <p><strong>Date:</strong> ${new Date(p.createdAt).toLocaleDateString()}</p>
      <p><strong>Status:</strong> ${p.status}</p>
      <table><tr><th>Medication</th><th>Dosage</th><th>Schedule</th><th>Duration</th><th>Instructions</th></tr>
      ${p.medications.map(m => `<tr>
        <td>${m.name}</td><td>${m.dosage}</td>
        <td>${[m.morning && 'Morn', m.afternoon && 'Aft', m.evening && 'Eve', m.night && 'Night'].filter(Boolean).join(', ')}</td>
        <td>${m.duration} ${m.durationUnit}</td>
        <td>${m.instructions || '-'}</td>
      </tr>`).join('')}
      </table>
      <div class="footer">Generated by VOA EMR</div>
      </body></html>
    `);
    w.document.close();
    w.print();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Prescriptions</h1>
          <p className="text-sm text-muted mt-1">{prescriptions.length} total prescriptions</p>
        </div>
        <button
          onClick={() => setShowBuilder(true)}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition-all"
        >
          <Plus className="w-4 h-4" />
          New Prescription
        </button>
      </div>

      {/* Search */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
        <input
          type="text"
          placeholder="Search by patient name..."
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          className="w-full pl-9 pr-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
        />
      </div>

      {/* Content */}
      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-6 h-6 animate-spin text-muted" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="rounded-xl border border-default bg-card-bg p-16 text-center">
          <Pill className="w-12 h-12 text-muted mx-auto mb-4" />
          <p className="text-sm text-muted">
            {searchQuery ? 'No prescriptions match your search' : 'No prescriptions yet'}
          </p>
          {!searchQuery && (
            <button
              onClick={() => setShowBuilder(true)}
              className="mt-4 inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:opacity-90 transition-all"
            >
              <Plus className="w-4 h-4" />
              Create your first prescription
            </button>
          )}
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map(p => {
            const sc = STATUS_CONFIG[p.status] || STATUS_CONFIG.draft;
            const StatusIcon = sc.icon;
            return (
              <div
                key={p._id}
                className="rounded-xl border border-default bg-card-bg p-4 hover:border-primary/20 transition-all"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="w-9 h-9 rounded-full bg-primary/10 flex items-center justify-center text-primary text-sm font-bold shrink-0">
                        {(p.patient?.name || 'P').charAt(0)}
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-foreground">{p.patient?.name || 'Unknown Patient'}</p>
                        <p className="text-xs text-muted">
                          <Clock className="w-3 h-3 inline mr-1" />
                          {new Date(p.createdAt).toLocaleDateString('en-US', {
                            month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit',
                          })}
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-wrap gap-1.5 mt-1">
                      {p.medications.slice(0, 3).map((m, i) => (
                        <span key={i} className="text-[11px] px-2 py-0.5 rounded-full bg-primary/5 text-muted-foreground border border-default">
                          {m.name}
                        </span>
                      ))}
                      {p.medications.length > 3 && (
                        <span className="text-[11px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground">
                          +{p.medications.length - 3} more
                        </span>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className={cn('text-[10px] px-2 py-0.5 rounded-full font-medium flex items-center gap-1', sc.color)}>
                      <StatusIcon className="w-3 h-3" />
                      {sc.label}
                    </span>
                    <button
                      onClick={() => handlePrint(p)}
                      title="Print"
                      className="p-1.5 rounded-lg hover:bg-hover text-muted hover:text-foreground transition-colors"
                    >
                      <Printer className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Prescription Builder Modal */}
      {showBuilder && (
        <PrescriptionBuilder
          onClose={() => setShowBuilder(false)}
          onSaved={() => { setShowBuilder(false); fetchPrescriptions(); }}
        />
      )}
    </div>
  );
}

function PrescriptionBuilder({
  onClose,
  onSaved,
}: {
  onClose: () => void;
  onSaved: () => void;
}) {
  const [patientQuery, setPatientQuery] = useState('');
  const [patients, setPatients] = useState<PatientProfile[]>([]);
  const [selectedPatient, setSelectedPatient] = useState<PatientProfile | null>(null);
  const [medications, setMedications] = useState<PrescriptionMedication[]>([emptyMedication()]);
  const [searching, setSearching] = useState(false);
  const [saving, setSaving] = useState(false);
  const [showPatientDropdown, setShowPatientDropdown] = useState(false);

  useEffect(() => {
    if (patientQuery.length < 2) { setPatients([]); return; }
    const timer = setTimeout(async () => {
      setSearching(true);
      try {
        const res = await patientService.search(patientQuery);
        setPatients(res.data.data || []);
      } catch { setPatients([]); }
      setSearching(false);
    }, 400);
    return () => clearTimeout(timer);
  }, [patientQuery]);

  const addMedication = () => setMedications(prev => [...prev, emptyMedication()]);

  const removeMedication = (index: number) => {
    if (medications.length === 1) return;
    setMedications(prev => prev.filter((_, i) => i !== index));
  };

  const updateMedication = (index: number, field: keyof PrescriptionMedication, value: unknown) => {
    setMedications(prev => prev.map((m, i) => i === index ? { ...m, [field]: value } : m));
  };

  const isValid = selectedPatient && medications.every(m => m.name.trim() && m.dosage.trim());

  const handleSave = async (status: 'draft' | 'active') => {
    if (!isValid) return;
    setSaving(true);
    try {
      await prescriptionService.create({
        patient: selectedPatient!._id as unknown as { _id: string; name: string; phone: string },
        medications,
        status,
      });
      toast.success(status === 'draft' ? 'Draft saved' : 'Prescription created & sent');
      onSaved();
    } catch { toast.error('Failed to save prescription'); }
    setSaving(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-10 pb-10 overflow-y-auto bg-black/40">
      <div className="w-full max-w-2xl rounded-xl border border-default bg-card-bg shadow-xl animate-slide-up">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-default">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            <h2 className="text-lg font-bold text-foreground">New Prescription</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-hover text-muted hover:text-foreground transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-5 max-h-[70vh] overflow-y-auto">
          {/* Patient Selector */}
          <div className="relative">
            <label className="block text-sm font-medium text-foreground mb-1.5">Patient</label>
            {selectedPatient ? (
              <div className="flex items-center justify-between rounded-lg border border-default px-3 py-2">
                <div className="flex items-center gap-2">
                  <div className="w-7 h-7 rounded-full bg-primary/10 flex items-center justify-center text-primary text-xs font-bold">
                    {selectedPatient.name.charAt(0)}
                  </div>
                  <span className="text-sm text-foreground font-medium">{selectedPatient.name}</span>
                  <span className="text-xs text-muted">{selectedPatient.phone}</span>
                </div>
                <button
                  onClick={() => { setSelectedPatient(null); setPatientQuery(''); }}
                  className="text-xs text-primary hover:underline"
                >
                  Change
                </button>
              </div>
            ) : (
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
                <input
                  type="text"
                  placeholder="Search patient by name or phone..."
                  value={patientQuery}
                  onChange={e => { setPatientQuery(e.target.value); setShowPatientDropdown(true); }}
                  onFocus={() => setShowPatientDropdown(true)}
                  className="w-full pl-9 pr-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
                />
                {showPatientDropdown && (patientQuery.length >= 2 || patients.length > 0) && (
                  <div className="absolute z-10 mt-1 w-full rounded-lg border border-default bg-card-bg shadow-lg max-h-48 overflow-y-auto">
                    {searching ? (
                      <div className="flex items-center justify-center py-4">
                        <Loader2 className="w-4 h-4 animate-spin text-muted" />
                      </div>
                    ) : patients.length === 0 ? (
                      <p className="text-xs text-muted text-center py-4">No patients found</p>
                    ) : (
                      patients.map(pt => (
                        <button
                          key={pt._id}
                          type="button"
                          onClick={() => { setSelectedPatient(pt); setShowPatientDropdown(false); setPatientQuery(''); }}
                          className="w-full flex items-center gap-2 px-3 py-2 text-sm text-foreground hover:bg-hover transition-colors text-left"
                        >
                          <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center text-primary text-[10px] font-bold">
                            {pt.name.charAt(0)}
                          </div>
                          <span className="font-medium">{pt.name}</span>
                          <span className="text-xs text-muted ml-auto">{pt.phone}</span>
                        </button>
                      ))
                    )}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Medications */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <label className="text-sm font-medium text-foreground">Medications</label>
              <button
                type="button"
                onClick={addMedication}
                className="flex items-center gap-1 text-xs text-primary hover:underline"
              >
                <Plus className="w-3 h-3" />
                Add medication
              </button>
            </div>
            <div className="space-y-4">
              {medications.map((med, i) => (
                <div key={i} className="rounded-lg border border-default p-4 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-medium text-muted">Medication #{i + 1}</span>
                    {medications.length > 1 && (
                      <button
                        type="button"
                        onClick={() => removeMedication(i)}
                        className="text-xs text-red-500 hover:underline"
                      >
                        Remove
                      </button>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <input
                      type="text"
                      placeholder="Medication name"
                      value={med.name}
                      onChange={e => updateMedication(i, 'name', e.target.value)}
                      className="col-span-2 sm:col-span-1 px-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                    <input
                      type="text"
                      placeholder="Dosage (e.g. 500mg)"
                      value={med.dosage}
                      onChange={e => updateMedication(i, 'dosage', e.target.value)}
                      className="px-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <fieldset>
                    <legend className="text-xs text-muted mb-1.5">Schedule</legend>
                    <div className="flex items-center gap-4">
                      {(['morning', 'afternoon', 'evening', 'night'] as const).map(period => (
                        <label key={period} className="flex items-center gap-1.5 text-sm text-foreground cursor-pointer">
                          <input
                            type="checkbox"
                            checked={med[period]}
                            onChange={e => updateMedication(i, period, e.target.checked)}
                            className="rounded border-default text-primary focus:ring-primary"
                          />
                          {period.charAt(0).toUpperCase() + period.slice(1)}
                        </label>
                      ))}
                    </div>
                  </fieldset>
                  <div className="grid grid-cols-3 gap-3">
                    <div className="col-span-1">
                      <input
                        type="text"
                        placeholder="Duration"
                        value={med.duration}
                        onChange={e => updateMedication(i, 'duration', e.target.value)}
                        className="w-full px-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
                      />
                    </div>
                    <div className="col-span-1">
                      <select
                        value={med.durationUnit}
                        onChange={e => updateMedication(i, 'durationUnit', e.target.value)}
                        className="w-full px-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                      >
                        {DURATION_UNITS.map(u => (
                          <option key={u} value={u}>{u}</option>
                        ))}
                      </select>
                    </div>
                    <div className="col-span-1">
                      <input
                        type="text"
                        placeholder="Instructions"
                        value={med.instructions}
                        onChange={e => updateMedication(i, 'instructions', e.target.value)}
                        className="w-full px-3 py-2 rounded-lg border border-default bg-card-bg text-sm text-foreground placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-primary"
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-default">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-sm text-muted hover:text-foreground hover:bg-hover transition-colors"
          >
            Cancel
          </button>
          <div className="flex items-center gap-2">
            <button
              type="button"
              disabled={!isValid || saving}
              onClick={() => handleSave('draft')}
              className="px-4 py-2 rounded-lg text-sm font-medium border border-default text-foreground hover:bg-hover transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Save Draft'}
            </button>
            <button
              type="button"
              disabled={!isValid || saving}
              onClick={() => handleSave('active')}
              className="px-4 py-2 rounded-lg text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 transition-all disabled:opacity-40 disabled:cursor-not-allowed flex items-center gap-1.5"
            >
              {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <><CheckCircle className="w-4 h-4" /> Create & Send</>}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
